Repository CA-G12/api-mostafa-hakim, pull requests merged in 2022-08, with the labels that each got.

#4 create structure for page and style it
  index.htm
  index.html
  style.css
Labels: approved

#7 create fetch function and the URL
  index.html
  main.js
Labels: approved

#8 This function buildDom
  dom.js
  index.html
  main.js
Labels: merg

#10 create wheather during week section and set data from api and style it
  dom.js
  index.html
  main.js
  style.css
Labels: waiting review

#12 create map and style it
  dom.js
  index.html
  main.js
  style.css
Labels: merg

#14 handle the apperance of the week section info
  dom.js
  index.html
  main.js
  style.css
Labels: approved

#16 find the max temp and min temp in week section and make the change ba…
  dom.js
  main.js
Labels: done

#18 create responsive page and final editing
  dom.js
  index.html
  main.js
  style.css
Labels: waiting review

#23 22 get red of unnecessary comments
  dom.js
  index.html
  main.js
  style.css
Labels: done
